custom:
  localEnv: ${file(./local.yml)}
# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ${self:custom.localEnv.myOrg}
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: conezone
# "service" is the name of this project. This will also be added to your AWS resource names.
service: backend

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  deploymentMethod: direct
  iam:
    role: ${self:custom.localEnv.myLambda}

functions:
  PostItem:
    handler: functions/PostItem/index.handler
    events:
      - httpApi:
          path: /item
          method: post
  DeleteItem:
    handler: functions/DeleteItem/index.handler
    events:
      - httpApi:
          path: /item/{id}
          method: delete
  GetItem:
    handler: functions/GetItems/index.handler
    events:
      - httpApi:
          path: /item
          method: get
  PutItem:
    handler: functions/PutItem/index.handler
    events:
      - httpApi:
          path: /item/{id}
          method: put
  GetItemById:
    handler: functions/GetItem/index.handler
    events:
      - httpApi:
          path: /item/{id}
          method: get
  

resources:
  Resources:
    MenuTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: 'conezonemenu-db'
        AttributeDefinitions:
          - AttributeName: 'pk'
            AttributeType: 'S'
          - AttributeName: 'sk'
            AttributeType: 'S'
        KeySchema:
          - AttributeName: 'pk'
            KeyType: 'HASH'
          - AttributeName: 'sk'
            KeyType: 'RANGE'
        BillingMode: PAY_PER_REQUEST